---
apiVersion: dracon/v1beta1
kind: Consumer
metadata:
  name: golang-project-elasticsearch-consumer
  labels: {}
spec:
  params: []
  resources: {inputs: [], outputs: []}
  steps:
  # run elasticsearch consumer
  - name: run-elasticsearch-consumer
    image: index.docker.io/thoughtmachine/dracon-consumer-elasticsearch:latest
    env: [
      {name: ELASTICSEARCH_URL, value: http://elasticsearch.dracon.svc:9200}
    ]
    command: ["/consume"]
    args: [
      "-in", "{{.ConsumerSourcePath}}",
      "-es-index", "dracon"
    ]
