---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: golang-project-git-source
  labels: {}
spec:
  inputs: {resources: [{name: git-source, type: git}]}
  outputs: {resources: [{name: source, type: storage}]}
  steps:
  - name: git-source
    image: index.docker.io/thoughtmachine/dracon-source-git:latest
    command: ["/git.sh"]
