---
# git+https config
apiVersion: dracon/v1beta1
kind: PipelineResource
metadata:
  name: "{{.RunID}}-git-github-oauth2-proxy"
  labels: {}
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/pusher/oauth2_proxy.git
---
# pipelinerun
apiVersion: dracon/v1beta1
kind: PipelineRun
metadata:
  name: "golang-project-{{.RunID}}"
  labels:
    project: dracon
spec:
  pipelineRef: {name: golang-project}
  params: []
  podTemplate: {}
  # serviceAccount: git-github-oauth2-proxy # replace with desired git source service account (if needed)
  resources:
  - {name: git-source, resourceRef: {name: "{{.RunID}}-git-github-oauth2-proxy"}} # replace with desired git source
  timeout: 1h0m0s
