---
apiVersion: dracon/v1beta1
kind: Pipeline
metadata:
  name: golang-project
  labels: {}
spec:
  params: []
  resources:
  - {type: git, name: git-source}
  tasks:
  # stage 1 - archive source
  - name: fetch-source
    taskRef: {name: golang-project-git-source}
    resources:
      inputs: [{name: git-source, resource: git-source}]
      outputs: []
  # stage 2 - run tools
  - name: gosec-producer
    runAfter: [fetch-source]
    taskRef: {name: golang-project-gosec-producer}
    params: []
    resources: {inputs: [], outputs: []}
  # stage 3 - enrichment
  - name: enricher
    runAfter: [gosec-producer]
    taskRef: {name: golang-project-enricher}
    resources: {inputs: [], outputs: []}
  # stage 4 - consumers
  - name: elasticsearch-consumer
    runAfter: [enricher]
    taskRef: {name: golang-project-elasticsearch-consumer}
    params:
    - name: dracon-start-time
      value: "$(tasks.fetch-source.results.dracon-start-time)"
    resources: {inputs: [], outputs: []}
