---
apiVersion: dracon/v1alpha1
kind: Enricher
metadata:
  name: python-project-enricher
  labels: {}
spec:
  inputs: {resources: []}
  outputs: {resources: []}
  steps:
  # run enricher
  - name: run-enricher
    image: thoughtmachine/dracon-enricher:latest
    imagePullPolicy: Never
    env:
    - name: ENRICHER_READ_PATH
      value: /workspace
    - name: ENRICHER_WRITE_PATH
      value: "{{.EnricherOutPath}}"
    - name: ENRICHER_DB_CONNECTION
      value: "postgresql://dracon:dracon@dracon-enrichment-db.dracon.svc?sslmode=disable"
    command: ["/enricher"]
