---
apiVersion: dracon/v1alpha1
kind: Pipeline
metadata:
  name: python-project
  labels: {}
spec:
  params: []
  resources:
  - {type: git, name: git-source}
  tasks:
  # stage 1 - archive source
  - name: fetch-source
    taskRef: {name: python-project-git-source}
    resources:
      inputs: [{name: git-source, resource: git-source}]
      outputs: []
  # stage 2 - run tools
  - name: bandit-producer
    runAfter: [fetch-source]
    taskRef: {name: python-project-bandit-producer}
    resources: {inputs: [], outputs: []}
  # stage 3 - enrichment
  - name: enricher
    runAfter: [bandit-producer]
    taskRef: {name: python-project-enricher}
    resources: {inputs: [], outputs: []}
  # stage 4 - consumers
  - name: elasticsearch-consumer
    runAfter: [enricher]
    taskRef: {name: python-project-elasticsearch-consumer}
    params: []
    resources: {inputs: [], outputs: []}
