go_library(
    name = "config",
    srcs = [
        "config.go",
    ],
    visibility = [
        "//consumers/jira_c/..."
    ],
)

go_library(
    name = "document",
    srcs = [
        "document.go",
    ],
    visibility = [
        "//consumers/jira_c/..."
    ],
)