---
apiVersion: dracon/v1alpha1
kind: Consumer
metadata:
  name: mixed-lang-project-elasticsearch-consumer
  labels: {}
spec:
  inputs: {resources: [], params: []}
  steps:
  # run elasticsearch consumer
  - name: run-elasticsearch-consumer
    image: index.docker.io/thoughtmachine/dracon-consumer-elasticsearch:latest
    env: []
    command: ["/consume"]
    args: [
      "-in", "{{.ConsumerSourcePath}}",
      "-es-urls", "http://elasticsearch.dracon.svc:9200",
      "-es-index", "dracon"
    ]
