---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dracon

commonLabels:
  app: dracon
  app.kubernetes.io/component: "pipeline"
  dracon.thoughtmachine.io/pipeline: "mixed-lang-project"

resources:
- elasticsearch-consumer.yaml
- enricher.yaml
- git-source.yaml
- gosec-producer.yaml
- bandit-producer.yaml
- spotbugs-producer.yaml
- pipeline-run.yaml
- pipeline.yaml
