---
apiVersion: dracon/v1alpha1
kind: Producer
metadata:
  name: mixed-lang-project-spotbugs-producer
  labels: {}
spec:
  inputs: {resources: [], params: []}
  outputs: {resources: []}
  volumes: []
  steps:
  # run spotbugs
  - name: run-spotbugs
    image: thoughtmachine/dracon-tool-spotbugs:latest
    command: ["sh"]
    args: ["-c",
      "spotbugs {{.ProducerSourcePath}} -output {{.ProducerToolOutPath}} -xml:withMessages"
    ]
    volumeMounts: []
  # parse results
  - name: parse-spotbugs
    image: thoughtmachine/dracon-producer-spotbugs:latest
    imagePullPolicy: Never
    command: ["/parse"]
    args: [
      "-in={{.ProducerToolOutPath}}",
      "-out={{.ProducerOutPath}}"
    ]
    volumeMounts: []
