---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: dracon
  labels:
    project: dracon
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2019-10-12T01-39-57Z
        command: ["sh"]
        args: ["-c", "mkdir -p /data/dracon && /usr/bin/minio server /data"]
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        ports:
        - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: minio-storage
  namespace: dracon
spec:
  type: ClusterIP
  ports:
    - port: 9000
  selector:
    app: minio
---
apiVersion: v1
kind: Secret
metadata:
  name: dracon-storage
  namespace: dracon
type: Opaque
data:
  # Generated by:
  # cat scripts/development/k8s/minio-storage/minio.conf | base64 -w 0
  boto_config: W0NyZWRlbnRpYWxzXQphd3NfYWNjZXNzX2tleV9pZCA9IG1pbmlvCmF3c19zZWNyZXRfYWNjZXNzX2tleSA9IG1pbmlvMTIzCnMzX3BvcnQgPSA5MDAwCltzM10KaG9zdCA9IG1pbmlvLXN0b3JhZ2UuZHJhY29uLnN2YwpjYWxsaW5nX2Zvcm1hdCA9IGJvdG8uczMuY29ubmVjdGlvbi5PcmRpbmFyeUNhbGxpbmdGb3JtYXQKW0JvdG9dCmh0dHBzX3ZhbGlkYXRlX2NlcnRpZmljYXRlcyA9IEZhbHNlCmlzX3NlY3VyZSA9IEZhbHNlCltHU1V0aWxdCnByZWZlcl9hcGkgPSB4bWwK
