filegroup(
    name = "cert-manager",
    srcs = [
        "cert-manager.yaml",
    ],
    visibility = ["//scripts/development/kind/..."],
)

filegroup(
    name = "ingress-nginx",
    srcs = [
        "ingress-nginx.yaml",
    ],
    visibility = ["//scripts/development/kind/..."],
)
