package jira

import (
	"testing"

	"github.com/andygrunwald/go-jira"
	"github.com/stretchr/testify/assert"
	"github.com/trivago/tgo/tcontainer"

	"github.com/thought-machine/dracon/consumers/jira_c/config"
)

var (
	sampleConfig = config.Config{
		DefaultValues: config.DefaultValues{
			Project:         "TOY",
			IssueType:       "Vulnerability",
			Components:      []string{"c1", "c2", "c3"},
			AffectsVersions: []string{"V1", "V2"},
			Labels:          []string(nil),
			CustomFields: []config.CustomField{{
				ID:        "customfield_10000",
				FieldType: "multi-value",
				Values:    []string{"foo", "bar"},
			}},
		},
		Mappings: []config.Mappings{{
			DraconField: "cvss",
			JiraField:   "customfield_10001",
			FieldType:   "float",
		}},
		DescriptionExtras: []string{"target", "tool_name"},
	}

	sampleResult = map[string]string{
		"scan_start_time": "0001-01-01T00:00:00Z",
		"scan_id":         "babbb83-4627-41c6-8ba0-70ee866290e9",
		"tool_name":       "spotbugs",
		"source":          "//foo/bar:baz",
		"target":          "//foo1/bar1:baz2",
		"type":            "test type",
		"title":           "Unit Test Title",
		"severity_text":   "Info",
		"cvss":            "0.000",
		"confidence_text": "Info",
		"description":     "this is a test description",
		"first_found":     "0001-01-01T00:00:00Z",
		"false_positive":  "true",
	}

	expIssue = jira.Issue{
		Fields: &jira.IssueFields{
			Project: jira.Project{
				Key: "TOY",
			},
			Type: jira.IssueType{
				Name: "Vulnerability",
			},
			Description: "This issue was automatically generated by the Dracon security pipeline.\n\n" +
				"*this is a test description*\n\n" +
				"{code:}\n" +
				"target:                    //foo1/bar1:baz2\n" +
				"tool_name:                 spotbugs\n" +
				"{code}\n",
			Summary: "bar1:baz2 Unit Test Title",
			Components: []*jira.Component{
				&jira.Component{Name: "c1"},
				&jira.Component{Name: "c2"},
				&jira.Component{Name: "c3"},
			},
			AffectsVersions: []*jira.AffectsVersion{
				&jira.AffectsVersion{Name: "V1"},
				&jira.AffectsVersion{Name: "V2"},
			},
			Labels: []string(nil),
			Unknowns: tcontainer.MarshalMap{
				"customfield_10000": []map[string]string{{"value": "foo"}, {"value": "bar"}},
				"customfield_10001": 0.000,
			},
		},
	}

	sampleClient = &client{
		JiraClient:    authJiraClient("test_user", "test_token", "test_url"),
		DryRunMode:    true,
		Config:        sampleConfig,
		DefaultFields: getDefaultFields(sampleConfig),
	}
)

func TestNewClient(t *testing.T) {
	client := NewClient("test_user", "test_token", "test_url", true, sampleConfig)
	assert.EqualValues(t, client, sampleClient)
}

func TestAuthJiraClient(t *testing.T) {
	client := authJiraClient("test_user", "test_token", "test_url")
	assert.NotEmpty(t, client)
}

func TestAssembleIssue(t *testing.T) {
	issue := sampleClient.assembleIssue(sampleResult)
	assert.EqualValues(t, issue, &expIssue)
}

func TestCreateIssue(t *testing.T) {
	err := sampleClient.CreateIssue(sampleResult)
	assert.NoError(t, err)
}
