apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName: "elasticsearch"
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
              name: client
            - containerPort: 9300
              name: nodes
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch
              subPath: es-data
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    service: elasticsearch
spec:
  ports:
    - port: 9200
      name: client
    - port: 9300
      name: nodes
  selector:
    app: elasticsearch
