proto_library(
    name = "v1",
    srcs = [
        "config.proto",
        "engine.proto",
        "issue.proto",
    ],
    languages = [
        "py",
        "go",
    ],
    visibility = ["PUBLIC"],
)
