---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dracon-enrichment-db
  labels:
    app: dracon-enrichment-db
    project: dracon
spec:
  revisionHistoryLimit: 3
  serviceName: dracon-enrichment-db
  replicas: 1
  selector:
    matchLabels:
      app: dracon-enrichment-db
      project: dracon
  template:
    metadata:
      labels:
        app: dracon-enrichment-db
        project: dracon
    spec:
      securityContext:
        fsGroup: 70
      containers:
        - name: dracon-enrichment-db
          image: postgres:alpine
          env:
            - name: POSTGRES_USER
              value: dracon
            - name: POSTGRES_PASSWORD
              value: dracon
          resources:
            requests:
              memory: 512Mi
              cpu: 0.5
            limits:
              memory: 5Gi
              cpu: 1
          ports:
            - containerPort: 5432
          securityContext:
            runAsUser: 70
            runAsGroup: 70
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: dracon-postgres
              subPath: postgres-db
  volumeClaimTemplates:
  - metadata:
      name: dracon-postgres
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dracon-enrichment-db
  labels:
    project: dracon
spec:
  ports:
    - port: 5432
  selector:
    app: dracon-enrichment-db
