subinclude("//build/defs:kustomize")

filegroup(
    name = "test-a",
    srcs = [
        "kustomization.yaml",
        "patch-pipeline.yaml",
        "resources.yaml",
    ],
    visibility = ["//docs/designs/dracon-v2/..."],
)
