---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret-consumer
  labels: {}
type: kubernetes.io/ssh-auth
data:
  # echo "FOO" | base64 -w 0
  MY_SECRET: Rk9PCg==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-secret-consumer
  labels: {}
secrets:
- name: my-secret-consumer
---
apiVersion: dracon/v1alpha1
kind: Consumer
metadata:
  name: secrets-consumer
  labels: {}
spec:
  inputs: {resources: [], params: []}
  steps:
  # run secrets consumer
  - name: run-secrets-consumer
    image: dracon/consumer/secrets:latest
    imagePullPolicy: Never
    env: [
      {name: MY_SECRET, valueFrom: {secretKeyRef: MY_SECRET}}
    ]
    command: ["/consume"]
    args: [
      "-in", "{{.ConsumerSourcePath}}",
    ]
---
# pipelinerun
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: "demo-secrets-{{.RunID}}"
  labels: {}
spec:
  pipelineRef: {name: demo}
  params: []
  podTemplate: {}
  serviceAccountNames:
    - my-secret-consumer
  resources: []
  timeout: 1h0m0s
