go_library(
    name = "document",
    srcs = [
        "document.go",
        "types.go",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//api/proto:v1",
        "//third_party/go:protobuf",
    ],
)
