go_library(
    name = "putil",
    srcs = [
        "load.go",
        "write.go",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//pkg/genproto/v1",
        "//third_party/go:gogo_protobuf",
        "//third_party/go:pkg_errors",
    ],
)
