subinclude("//build/defs:kustomize")

filegroup(
    name = "test-b",
    srcs = [
        "kustomization.yaml",
        "resources.yaml",
        "patch-pipeline.yaml",
    ],
    visibility = ["//docs/..."],
)
