# TODO(hjenkins) this should be a generated using proto_libary() build rule
go_library(
    name = "v1",
    srcs = [
        "config.pb.go",
        "engine.pb.go",
        "issue.pb.go",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//third_party/go:golang_protobuf",
    ],
)
