// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// WrapperArgs consists of a specific params for a producer wrapper
type WrapperArgs struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Output               string   `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WrapperArgs) Reset()         { *m = WrapperArgs{} }
func (m *WrapperArgs) String() string { return proto.CompactTextString(m) }
func (*WrapperArgs) ProtoMessage()    {}
func (*WrapperArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

func (m *WrapperArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WrapperArgs.Unmarshal(m, b)
}
func (m *WrapperArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WrapperArgs.Marshal(b, m, deterministic)
}
func (m *WrapperArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WrapperArgs.Merge(m, src)
}
func (m *WrapperArgs) XXX_Size() int {
	return xxx_messageInfo_WrapperArgs.Size(m)
}
func (m *WrapperArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_WrapperArgs.DiscardUnknown(m)
}

var xxx_messageInfo_WrapperArgs proto.InternalMessageInfo

func (m *WrapperArgs) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *WrapperArgs) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

// Config consists of params required by a producer in order to run
type Config struct {
	WrapperArgs *WrapperArgs `protobuf:"bytes,1,opt,name=wrapperArgs,proto3" json:"wrapperArgs,omitempty"`
	// specific arguments for the wrapped executable
	ToolArgs             map[string]string `protobuf:"bytes,2,rep,name=toolArgs,proto3" json:"toolArgs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetWrapperArgs() *WrapperArgs {
	if m != nil {
		return m.WrapperArgs
	}
	return nil
}

func (m *Config) GetToolArgs() map[string]string {
	if m != nil {
		return m.ToolArgs
	}
	return nil
}

func init() {
	proto.RegisterType((*WrapperArgs)(nil), "dracon.v1.WrapperArgs")
	proto.RegisterType((*Config)(nil), "dracon.v1.Config")
	proto.RegisterMapType((map[string]string)(nil), "dracon.v1.Config.ToolArgsEntry")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0x29, 0x4a, 0x4c, 0xce, 0xcf,
	0xd3, 0x2b, 0x33, 0x54, 0xb2, 0xe5, 0xe2, 0x0e, 0x2f, 0x4a, 0x2c, 0x28, 0x48, 0x2d, 0x72, 0x2c,
	0x4a, 0x2f, 0x16, 0x12, 0xe3, 0x62, 0x2b, 0x49, 0x2c, 0x4a, 0x4f, 0x2d, 0x91, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x40, 0xe2, 0xf9, 0xa5, 0x25, 0x05, 0xa5, 0x25, 0x12, 0x4c, 0x10,
	0x71, 0x08, 0x4f, 0x69, 0x0f, 0x23, 0x17, 0x9b, 0x33, 0xd8, 0x68, 0x21, 0x0b, 0x2e, 0xee, 0x72,
	0x84, 0x49, 0x60, 0xfd, 0xdc, 0x46, 0x62, 0x7a, 0x70, 0xab, 0xf4, 0x90, 0xec, 0x09, 0x42, 0x56,
	0x2a, 0x64, 0xcd, 0xc5, 0x51, 0x92, 0x9f, 0x9f, 0x03, 0xd6, 0xc6, 0xa4, 0xc0, 0xac, 0xc1, 0x6d,
	0x24, 0x8f, 0xa4, 0x0d, 0x62, 0xbc, 0x5e, 0x08, 0x54, 0x85, 0x6b, 0x5e, 0x49, 0x51, 0x65, 0x10,
	0x5c, 0x83, 0x94, 0x35, 0x17, 0x2f, 0x8a, 0x94, 0x90, 0x00, 0x17, 0x73, 0x76, 0x6a, 0x25, 0xd4,
	0xfd, 0x20, 0xa6, 0x90, 0x08, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69, 0x2a, 0xd4, 0xed, 0x10, 0x8e,
	0x15, 0x93, 0x05, 0xa3, 0x13, 0x4b, 0x14, 0x53, 0x99, 0x61, 0x12, 0x1b, 0x38, 0x54, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x26, 0x12, 0xcf, 0xcd, 0x25, 0x01, 0x00, 0x00,
}
