// Code generated by protoc-gen-go. DO NOT EDIT.
// source: engine.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//Scan related information, unique and immutable per scan run
//This message is copied from LaunchToolRequest to LaunchToolResponse
//by each producer wrapper
type ScanInfo struct {
	// scan unique identifier
	ScanUuid string `protobuf:"bytes,1,opt,name=scan_uuid,json=scanUuid,proto3" json:"scan_uuid,omitempty"`
	// timestamp of when the scan was triggered (passed to LaunchToolResponse)
	ScanStartTime        *timestamp.Timestamp `protobuf:"bytes,2,opt,name=scan_start_time,json=scanStartTime,proto3" json:"scan_start_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ScanInfo) Reset()         { *m = ScanInfo{} }
func (m *ScanInfo) String() string { return proto.CompactTextString(m) }
func (*ScanInfo) ProtoMessage()    {}
func (*ScanInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_770b178c3aab763f, []int{0}
}

func (m *ScanInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanInfo.Unmarshal(m, b)
}
func (m *ScanInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanInfo.Marshal(b, m, deterministic)
}
func (m *ScanInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanInfo.Merge(m, src)
}
func (m *ScanInfo) XXX_Size() int {
	return xxx_messageInfo_ScanInfo.Size(m)
}
func (m *ScanInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ScanInfo proto.InternalMessageInfo

func (m *ScanInfo) GetScanUuid() string {
	if m != nil {
		return m.ScanUuid
	}
	return ""
}

func (m *ScanInfo) GetScanStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.ScanStartTime
	}
	return nil
}

// LaunchToolRequest consists of a request configuration,
// built by the engine and processed by a producer,
// through which options are passed
type LaunchToolRequest struct {
	ScanInfo             *ScanInfo `protobuf:"bytes,1,opt,name=scan_info,json=scanInfo,proto3" json:"scan_info,omitempty"`
	Config               *Config   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LaunchToolRequest) Reset()         { *m = LaunchToolRequest{} }
func (m *LaunchToolRequest) String() string { return proto.CompactTextString(m) }
func (*LaunchToolRequest) ProtoMessage()    {}
func (*LaunchToolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_770b178c3aab763f, []int{1}
}

func (m *LaunchToolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LaunchToolRequest.Unmarshal(m, b)
}
func (m *LaunchToolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LaunchToolRequest.Marshal(b, m, deterministic)
}
func (m *LaunchToolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LaunchToolRequest.Merge(m, src)
}
func (m *LaunchToolRequest) XXX_Size() int {
	return xxx_messageInfo_LaunchToolRequest.Size(m)
}
func (m *LaunchToolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LaunchToolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LaunchToolRequest proto.InternalMessageInfo

func (m *LaunchToolRequest) GetScanInfo() *ScanInfo {
	if m != nil {
		return m.ScanInfo
	}
	return nil
}

func (m *LaunchToolRequest) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

// LaunchToolReponse consists of a response built by a producer,
// to be interpreted by a consumer
type LaunchToolResponse struct {
	ScanInfo *ScanInfo `protobuf:"bytes,1,opt,name=scan_info,json=scanInfo,proto3" json:"scan_info,omitempty"`
	// The name of the tool that ran the scan
	ToolName string `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Issues discovered during the scan
	Issues               []*Issue `protobuf:"bytes,3,rep,name=issues,proto3" json:"issues,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LaunchToolResponse) Reset()         { *m = LaunchToolResponse{} }
func (m *LaunchToolResponse) String() string { return proto.CompactTextString(m) }
func (*LaunchToolResponse) ProtoMessage()    {}
func (*LaunchToolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_770b178c3aab763f, []int{2}
}

func (m *LaunchToolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LaunchToolResponse.Unmarshal(m, b)
}
func (m *LaunchToolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LaunchToolResponse.Marshal(b, m, deterministic)
}
func (m *LaunchToolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LaunchToolResponse.Merge(m, src)
}
func (m *LaunchToolResponse) XXX_Size() int {
	return xxx_messageInfo_LaunchToolResponse.Size(m)
}
func (m *LaunchToolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LaunchToolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LaunchToolResponse proto.InternalMessageInfo

func (m *LaunchToolResponse) GetScanInfo() *ScanInfo {
	if m != nil {
		return m.ScanInfo
	}
	return nil
}

func (m *LaunchToolResponse) GetToolName() string {
	if m != nil {
		return m.ToolName
	}
	return ""
}

func (m *LaunchToolResponse) GetIssues() []*Issue {
	if m != nil {
		return m.Issues
	}
	return nil
}

//
//An EnrichedLaunchToolResponse consists of deduplicated vulnerability
//information, with added metadata for consumers
type EnrichedLaunchToolResponse struct {
	// The results of the original scan prior to enrichment
	OriginalResults *LaunchToolResponse `protobuf:"bytes,1,opt,name=original_results,json=originalResults,proto3" json:"original_results,omitempty"`
	// Enriched, deduplicated issues
	Issues               []*EnrichedIssue `protobuf:"bytes,2,rep,name=issues,proto3" json:"issues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EnrichedLaunchToolResponse) Reset()         { *m = EnrichedLaunchToolResponse{} }
func (m *EnrichedLaunchToolResponse) String() string { return proto.CompactTextString(m) }
func (*EnrichedLaunchToolResponse) ProtoMessage()    {}
func (*EnrichedLaunchToolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_770b178c3aab763f, []int{3}
}

func (m *EnrichedLaunchToolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrichedLaunchToolResponse.Unmarshal(m, b)
}
func (m *EnrichedLaunchToolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrichedLaunchToolResponse.Marshal(b, m, deterministic)
}
func (m *EnrichedLaunchToolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrichedLaunchToolResponse.Merge(m, src)
}
func (m *EnrichedLaunchToolResponse) XXX_Size() int {
	return xxx_messageInfo_EnrichedLaunchToolResponse.Size(m)
}
func (m *EnrichedLaunchToolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrichedLaunchToolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnrichedLaunchToolResponse proto.InternalMessageInfo

func (m *EnrichedLaunchToolResponse) GetOriginalResults() *LaunchToolResponse {
	if m != nil {
		return m.OriginalResults
	}
	return nil
}

func (m *EnrichedLaunchToolResponse) GetIssues() []*EnrichedIssue {
	if m != nil {
		return m.Issues
	}
	return nil
}

func init() {
	proto.RegisterType((*ScanInfo)(nil), "dracon.v1.ScanInfo")
	proto.RegisterType((*LaunchToolRequest)(nil), "dracon.v1.LaunchToolRequest")
	proto.RegisterType((*LaunchToolResponse)(nil), "dracon.v1.LaunchToolResponse")
	proto.RegisterType((*EnrichedLaunchToolResponse)(nil), "dracon.v1.EnrichedLaunchToolResponse")
}

func init() { proto.RegisterFile("engine.proto", fileDescriptor_770b178c3aab763f) }

var fileDescriptor_770b178c3aab763f = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xbf, 0x4e, 0xf3, 0x30,
	0x14, 0xc5, 0x95, 0xf6, 0x53, 0xd5, 0x38, 0xfd, 0xd4, 0x36, 0x2c, 0x51, 0x2a, 0x44, 0x95, 0x29,
	0x2c, 0xe9, 0x1f, 0xde, 0xa0, 0x08, 0x89, 0x4a, 0x88, 0xc1, 0x2d, 0x0b, 0x4b, 0xe4, 0x26, 0x4e,
	0x6a, 0x91, 0xfa, 0x86, 0xd8, 0xee, 0x5b, 0xb0, 0xf3, 0xb8, 0x28, 0x8e, 0x53, 0x05, 0xc1, 0xc4,
	0xe8, 0x73, 0xee, 0xb9, 0xe7, 0x77, 0x65, 0x34, 0xa2, 0x3c, 0x67, 0x9c, 0x46, 0x65, 0x05, 0x12,
	0x5c, 0x3b, 0xad, 0x48, 0x02, 0x3c, 0x3a, 0xaf, 0x7c, 0x87, 0x09, 0xa1, 0x8c, 0xee, 0x8f, 0x12,
	0xe0, 0x19, 0xcb, 0xcd, 0xeb, 0x26, 0x07, 0xc8, 0x0b, 0xba, 0xd0, 0xaf, 0x83, 0xca, 0x16, 0x92,
	0x9d, 0xa8, 0x90, 0xe4, 0x54, 0x36, 0x03, 0xc1, 0x1b, 0x1a, 0xee, 0x12, 0xc2, 0xb7, 0x3c, 0x03,
	0x77, 0x86, 0x6c, 0x91, 0x10, 0x1e, 0x2b, 0xc5, 0x52, 0xcf, 0x9a, 0x5b, 0xa1, 0x8d, 0x87, 0xb5,
	0xf0, 0xa2, 0x58, 0xea, 0x6e, 0xd0, 0x58, 0x9b, 0x42, 0x92, 0x4a, 0xc6, 0xf5, 0x1a, 0xaf, 0x37,
	0xb7, 0x42, 0x67, 0xed, 0x47, 0x4d, 0x47, 0xd4, 0x76, 0x44, 0xfb, 0xb6, 0x03, 0xff, 0xaf, 0x23,
	0xbb, 0x3a, 0x51, 0x6b, 0x41, 0x89, 0xa6, 0x4f, 0x44, 0xf1, 0xe4, 0xb8, 0x07, 0x28, 0x30, 0x7d,
	0x57, 0x54, 0x48, 0x77, 0x69, 0x5a, 0x19, 0xcf, 0x40, 0xb7, 0x3a, 0xeb, 0xab, 0xe8, 0x72, 0x5c,
	0xd4, 0xd2, 0x35, 0x28, 0x9a, 0xf3, 0x16, 0x0d, 0x9a, 0x23, 0x0d, 0xc1, 0xb4, 0x33, 0x7e, 0xaf,
	0x0d, 0x6c, 0x06, 0x82, 0x0f, 0x0b, 0xb9, 0xdd, 0x4a, 0x51, 0x02, 0x17, 0xf4, 0x0f, 0x9d, 0x33,
	0x64, 0x4b, 0x80, 0x22, 0xe6, 0xc4, 0x1c, 0x6e, 0xe3, 0x61, 0x2d, 0x3c, 0x93, 0x13, 0x75, 0x43,
	0x34, 0xd0, 0x5f, 0x20, 0xbc, 0xfe, 0xbc, 0x1f, 0x3a, 0xeb, 0x49, 0x67, 0xd7, 0xb6, 0x36, 0xb0,
	0xf1, 0x83, 0x4f, 0x0b, 0xf9, 0x0f, 0xbc, 0x62, 0xc9, 0x91, 0xa6, 0xbf, 0x70, 0x3d, 0xa2, 0x09,
	0x54, 0x2c, 0x67, 0x9c, 0x14, 0x71, 0x45, 0x85, 0x2a, 0xa4, 0x30, 0x78, 0xd7, 0x9d, 0x95, 0x3f,
	0x83, 0x78, 0xdc, 0xc6, 0x70, 0x93, 0x72, 0x97, 0x17, 0xa4, 0x9e, 0x46, 0xf2, 0x3a, 0xf9, 0x16,
	0xe0, 0x1b, 0xda, 0xe6, 0xdf, 0x6b, 0xef, 0xbc, 0x3a, 0x0c, 0xf4, 0x2f, 0xde, 0x7d, 0x05, 0x00,
	0x00, 0xff, 0xff, 0xcb, 0x29, 0x3f, 0x03, 0x6d, 0x02, 0x00, 0x00,
}
