# filegroup(
#     name = "patches",
#     srcs = glob(["*.yaml"]),
#     visibility = ["//pkg/template/..."],
# )

filegroup(
    name = "patches",
    srcs = ["blank.yaml"],
    visibility = ["//pkg/template/..."],
)
