---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: golang-project-enricher
  labels: {}
spec:
  resources: {inputs: [], outputs: []}
  # inputs: {resources: []}
  # outputs: {resources: []}
  steps:
  # run enricher
  - name: run-enricher
    image: index.docker.io/thoughtmachine/dracon-enricher:latest
    env:
    - name: ENRICHER_READ_PATH
      value: $(workspaces.source.path)/.dracon/raw
    - name: ENRICHER_WRITE_PATH
      value: $(workspaces.source.path)/.dracon/enriched
    - name: ENRICHER_DB_CONNECTION
      value: "postgresql://dracon:dracon@dracon-enrichment-db.dracon.svc?sslmode=disable"
    command: ["/enricher"]
  workspaces:
  - name: source
    mountPath: /workspace/source
