---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dracon

commonLabels:
  app: dracon
  app.kubernetes.io/component: "pipeline"
  dracon.thoughtmachine.io/pipeline: "golang-project"

resources:
- elasticsearch-consumer.yaml
- enricher.yaml
- git-source.yaml
- gosec-producer.yaml
- pipeline-run.yaml
- pipeline.yaml
- third_party/k8s/git-clone.yaml

patches:
- patch: |-
    - op: move
      from: /metadata/name
      path: /metadata/generateName
  target:
      kind: PipelineRun
