subinclude("//build/defs:kustomize")

filegroup(
    name = "gosec-producer",
    srcs = [
        "gosec-producer.yaml",
        "kustomization.yaml",
        "patch-pipeline.yaml",
    ],
    visibility = ["//docs/designs/dracon-v2/..."],
)
