subinclude("//build/defs:kustomize")

filegroup(
    name = "gosec-producer",
    srcs = [
        "kustomization.yaml",
        "gosec-producer.yaml",
        "patch-pipeline.yaml",
    ],
    visibility = ["//docs/..."],
)
